### ISSUE TITLE
データベースの定義

### ISSUE THREAD

**Issue by yusukeyama** [tech-is/NANPA#40]
## データベースの各テーブルについて
気になった事を箇条書きで挙げていきます。
詳しい仕様は把握していないので、ざっくりとなので、摘便コメントで指摘していただければと。

1. goodテーブルは他のテーブルと同じように複数形が良いと思います（good->goods）
2. 各テーブルのidはAUTOINCREMENTをつけたほうが良いです。insertするときに自動で連番うってくれる感じです。
3. postsテーブルは投稿されたものを格納する感じだと思うので、createdやmodifiedなどの作成時刻、変更時刻などのカラムが必要かなと思うのですがいかがでしょうか。

以上な感じになります。よろしくおねがいします。

**Comment by taka-sho0220** [comment]
内容承知しました。
私自身は1,2は記述の通りに直して、3の部分も記述の通り、
・作成時刻=created_at
・変更時刻=update_at
のようにしてテーブル作成をしたらいいと思います。自分はreadmeをそのようにして追記しますので、sql担当していただいている田中さんが上記のように再度訂正していただいたsql文をgitに挙げていただくのがよろしいかと思いますが、皆さんどうでしょうか？

**Comment by yusukeyama** [comment]
auto incrementはたしかに下のほうでaltertableしてましたね・・・なので2番はそのままで大丈夫です。

**Comment by oohiramasayuki** [comment]
readme確認しました。ありがとうございます。
そのように進めてもらえればと思います。宜しくお願いします。

**Comment by yusukeyama** [comment]
プロジェクト完了したのでクローズ
